# Generated by Django 5.0.6 on 2024-05-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myworkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="date_created",
            new_name="date",
        ),
    ]
