# Generated by Django 5.0.6 on 2024-05-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myworkout", "0002_rename_date_created_exercise_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TargetBodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="required_equipment",
            field=models.ManyToManyField(to="myworkout.requiredequipment"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_body_part",
            field=models.ManyToManyField(to="myworkout.targetbodypart"),
        ),
    ]
